### ISSUE TITLE
Unknown option: rule-list

### ISSUE THREAD

**Issue by erikpaasonen** [Tufin/scripts#3]
Here is my (sanitized) syntax:
/usr/bin/perl ./apg_run_script.pl -device-name 'name_of_device' -policy-package 'policy1' -rule-list 34,35

We're running 15-4 HF2 on TufinOS 2.10 with the post-2.10 hotfix applied. I've verified that the strings inside the quotes do in fact match what is in the database tables. The help text says either "34,35" or "34-35" will work when specifying the rule list. However whenever I try to use the "-rule-list" option I get the output quoted below. Please help!

INFO
INFO  ----> Welcome to the APG multiple job creation script version 1.0.
INFO  ---->
Unknown option: rule-list
INFO  ----> Number of days of analysis not specified, assuming APG job duration of 6 months.
INFO  ----> Either Source or Destination zones is not defined, assuming global.
ERROR ----> No rules specified.

HELP has been requested.

 Program        : APG run multiple job script
 Author         : Stephane PEREZ (stephane.perez@tufin.com)
 Date           : 4 September 2015

 Version        : 1.0

 Usage : apg_run_script.pl -device-name <management name> [-policy-package <Name of the policy package>]
                        -rule-list <list of rules number>
                        -duration <number of days for analysis>
                        [-debug ] [-help]
Parameters details:
        rule-list                : The list of rules on which the user wish to run APG on in the form
                                 Accepted forms : 1,2-4
                        [-help]
Goodbye!

**Comment by erikpaasonen** [comment]
Possible fix is to update line 69 to replace "rules" inside the string with "rule-list", but not sure if that's what is intended.

**Comment by stephanepe** [comment]
Hi Erik,

 I found the bug in the documentation.

the syntax should be : 

/usr/bin/perl ./apg_run_script.pl -device-name 'name_of_device' -policy-package 'policy1' -rule-list 1-10,34,35

I updated the script too.

Stéphane
